.PHONY: all clean

all: README.md

README.md: guessinggame.sh
	@echo "# Guessing Game in Bash" > README.md
	@echo "" >> README.md
	@echo "Generated by \`make\` on $$(date)" >> README.md
	@echo "" >> README.md
	@echo "Number of lines in \`guessinggame.sh\`: $$(wc -l < guessinggame.sh)" >> README.md
	@echo "" >> README.md
	@echo "Run with: \`bash guessinggame.sh\`" >> README.md

clean:
	@rm -f README.md
